from . import terrains as terrain_gen
from isaaclab.terrains import FlatPatchSamplingCfg, TerrainGeneratorCfg

ROUGH_TERRAINS_CFG = TerrainGeneratorCfg(
    seed=0,
    size=(8.0, 8.0),
    border_width=3,
    num_rows=10,
    num_cols=20,
    horizontal_scale=0.05,
    vertical_scale=0.005,
    slope_threshold=1.0,
    use_cache=False,
    curriculum=True,
    sub_terrains={
        "perlin_rough": terrain_gen.PerlinPlaneTerrainCfg(
            proportion=0.20,
            noise_scale=[0.0, 0.1],
            noise_frequency=20,
            fractal_octaves=2,
            fractal_lacunarity=2.0,
            fractal_gain=0.25,
            centering=True,
            # wall_prob=[0.1, 0.1, 0.1, 0.1],
            # wall_height=5.0,
            # wall_thickness=0.05,
            flat_patch_sampling={
                "target": FlatPatchSamplingCfg(
                    num_patches=50,
                    patch_radius=[0.05, 0.10, 0.15, 0.20],
                    max_height_diff=0.05,
                    x_range=(-6.0, 6.0),
                    y_range=(-6.0, 6.0),
                ),
            },
        ),
        "square_gaps_easy": terrain_gen.PerlinSquareGapTerrainCfg(
            proportion=0.2,
            gap_distance_range=(0.05, 0.40),
            gap_depth=(0.20, 0.45),
            platform_width=2.8,
            border_width=1.0,
            # wall_prob=[0.1, 0.1, 0.1, 0.1],
            # wall_height=5.0,
            # wall_thickness=0.05,
            flat_patch_sampling={
                "target": FlatPatchSamplingCfg(
                    num_patches=50,
                    patch_radius=0.3,
                    max_height_diff=0.05,
                    x_range=(-6.0, 6.0),
                    y_range=(-6.0, 6.0),
                ),
            },
        ),
        "square_gaps_hard": terrain_gen.PerlinSquareGapTerrainCfg(
            proportion=0.20,
            gap_distance_range=(0.25, 0.95),
            gap_depth=(0.45, 0.90),
            platform_width=2.0,
            border_width=1.0,
            # wall_prob=[0.1, 0.1, 0.1, 0.1],
            # wall_height=5.0,
            # wall_thickness=0.05,
            flat_patch_sampling={
                "target": FlatPatchSamplingCfg(
                    num_patches=50,
                    patch_radius=0.3,
                    max_height_diff=0.05,
                    x_range=(-6.0, 6.0),
                    y_range=(-6.0, 6.0),
                ),
            },
        ),
        "stairs_up_down": terrain_gen.PerlinStairsUpDownTerrainCfg(
            proportion=0.10,
            per_step_height=(0.04, 0.20),
            per_step_width=3.8,
            per_step_length=(0.36, 0.24),
            num_steps=(2, 6),
            platform_length=1.0,
            border_width=1.0,
            # wall_prob=[0.1, 0.1, 0.1, 0.1],
            # wall_height=5.0,
            # wall_thickness=0.05,
            perlin_cfg=terrain_gen.PerlinPlaneTerrainCfg(
                noise_scale=0.02,
                noise_frequency=20,
                fractal_octaves=2,
                fractal_lacunarity=2.0,
                fractal_gain=0.25,
                centering=True,
            ),
            flat_patch_sampling={
                "target": FlatPatchSamplingCfg(
                    num_patches=50,
                    patch_radius=[0.15, 0.20],
                    max_height_diff=0.05,
                    y_range=(-6.0, 6.0),
                    x_range=(-1.0, 1.0),
                ),
            },
        ),
        "stairs_down_up": terrain_gen.PerlinStairsDownUpTerrainCfg(
            proportion=0.10,
            per_step_height=(0.04, 0.20),
            per_step_width=3.8,
            per_step_length=(0.36, 0.24),
            num_steps=(2, 6),
            platform_length=1.0,
            border_width=1.0,
            # wall_prob=[0.1, 0.1, 0.1, 0.1],
            # wall_height=5.0,
            # wall_thickness=0.05,
            perlin_cfg=terrain_gen.PerlinPlaneTerrainCfg(
                noise_scale=0.02,
                noise_frequency=20,
                fractal_octaves=2,
                fractal_lacunarity=2.0,
                fractal_gain=0.25,
                centering=True,
            ),
            flat_patch_sampling={
                "target": FlatPatchSamplingCfg(
                    num_patches=50,
                    patch_radius=[0.15, 0.20],
                    max_height_diff=0.05,
                    y_range=(-6.0, 6.0),
                    x_range=(-1.0, 1.0),
                ),
            },
        ),
        "pyramid_stairs_high": terrain_gen.PerlinPyramidStairsTerrainCfg(
            proportion=0.1,
            step_height_range=(0.08, 0.45),
            step_width=1.2,
            platform_width=3.5,
            border_width=1.0,
            # wall_prob=[0.1, 0.1, 0.1, 0.1],
            # wall_height=5.0,
            # wall_thickness=0.05,
            perlin_cfg=terrain_gen.PerlinPlaneTerrainCfg(
                noise_scale=0.02,
                noise_frequency=20,
                fractal_octaves=2,
                fractal_lacunarity=2.0,
                fractal_gain=0.25,
                centering=True,
            ),
            flat_patch_sampling={
                "target": FlatPatchSamplingCfg(
                    num_patches=50,
                    patch_radius=0.25,
                    max_height_diff=0.05,
                    y_range=(-6.0, 6.0),
                    x_range=(-1.0, 1.0),
                ),
            },
        ),
        "pyramid_stairs_inv_high": terrain_gen.PerlinInvertedPyramidStairsTerrainCfg(
            proportion=0.1,
            step_height_range=(0.08, 0.45),
            step_width=1.2,
            platform_width=3.5,
            border_width=1.0,
            # wall_prob=[0.1, 0.1, 0.1, 0.1],
            # wall_height=5.0,
            # wall_thickness=0.05,
            perlin_cfg=terrain_gen.PerlinPlaneTerrainCfg(
                noise_scale=0.02,
                noise_frequency=20,
                fractal_octaves=2,
                fractal_lacunarity=2.0,
                fractal_gain=0.25,
                centering=True,
            ),
            flat_patch_sampling={
                "target": FlatPatchSamplingCfg(
                    num_patches=50,
                    patch_radius=0.25,
                    max_height_diff=0.05,
                    y_range=(-6.0, 6.0),
                    x_range=(-1.0, 1.0),
                ),
            },
        ),
    },
)